name: run unit tests of features branches

on:
  push:
    branches:
    'feature/*'
    
jobs:
  run-unit-test:
    run-on: ubuntu-lastest
    
    steps:
     - name: Checkout
       uses: actions/checkout@v3.5.3
       
     -name: run unit test
      run: mvn test
